apiVersion: v1
kind: Namespace
metadata:
  name: homework

---

apiVersion: v1
kind: Pod
metadata:
  name: homework-1
  namespace: homework
  labels:
    app: hw
    tier: gold
  annotations:
    purpose: "homework"
spec:
  containers:
  - image: shekeriev/k8s-oracle
    name: homework-1-container
    
---

apiVersion: v1
kind: Pod
metadata:
  name: homework-2
  namespace: homework
  labels:
    app: hw
  annotations:
    purpose: "homework"
spec:
  containers:
  - image: shekeriev/k8s-oracle
    name: homework-2-container
    
---

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: hw
  name: homework-svc
  namespace: homework
spec:
  ports:
  - port: 80
    nodePort: 32000 
    targetPort: 5500
    protocol: TCP    
  selector:
    app: hw
  type: NodePort
status:
  loadBalancer: {}    
