apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: devguru
  namespace: projectx
rules:
- apiGroups:
  - ""
  - extensions
  - apps
  resources:
  - pods
  - services
  - deployments
  - replicasets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete  
---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: devguru
  namespace: projectx
subjects:
- kind: Group
  name: Gurus
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: devguru
  apiGroup: rbac.authorization.k8s.io