apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: production-
commonLabels:
  variant: production
  org: pirocorp
resources:
- ../../base
patchesStrategicMerge:
- deployment.yaml
- service.yaml
